version: "3"

services:
  app:
    image: library-test:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  redis:
    image: redis:7.2-alpine

  celery_worker:
    build: .
    command: celery -A library worker --loglevel=info
    depends_on:
      - db
      - app
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A library beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - app
      - redis
    env_file:
      - .env
